using System;
using DG.Tweening;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Rendering;

namespace Blobs.Presentation
{
    /// <summary>
    /// Owns the presentation-only timeline for a normal merge. All fields are intentionally
    /// inspector-tunable so timing and deformation can be art-directed before final VFX art exists.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class MergeAnimationOrchestrator : MonoBehaviour
    {
        [Header("Timing")]
        [SerializeField, Min(0.01f)] private float _anticipationDuration = 0.09f;
        [SerializeField, Min(0.01f)] private float _travelDuration = 0.18f;
        [SerializeField, Min(0.01f)] private float _consumeDuration = 0.11f;
        [SerializeField, Min(0.01f)] private float _settleDuration = 0.18f;

        [Header("Deformation")]
        [SerializeField, Min(0f)] private float _anticipationBackstep = 0.08f;
        [SerializeField] private Vector2 _anticipationScale = new(1.10f, 0.88f);
        [SerializeField] private Vector2 _travelScale = new(0.92f, 1.12f);
        [SerializeField] private Vector2 _targetBraceScale = new(1.06f, 0.94f);
        [SerializeField] private Vector2 _survivorImpactScale = new(1.14f, 0.86f);

        [Header("Impact VFX")]
        [Tooltip("Scene-authored effect prefab containing the particle, flash, and ring layers.")]
        [SerializeField] private MergeImpactVfx _mergeImpactPrefab;
        [SerializeField] private Transform _effectsRoot;

        [Header("Merge Sorting")]
        [SerializeField, Min(1)] private int _sourceSortingOffset = 10;
        [SerializeField, Min(1)] private int _targetSortingOffset = 20;
        [SerializeField, Min(1)] private int _effectSortingOffset = 10;

        [Header("Impact Audio")]
        [Tooltip("Assign the orchestrated merge impact clip here. No clip is generated by this component.")]
        [SerializeField] private AudioClip _mergeImpactClip;
        [SerializeField, Range(0f, 1f)] private float _mergeImpactVolume = 0.85f;
        [SerializeField, Range(0.1f, 3f)] private float _mergeImpactPitch = 1f;

        [Header("Rock Contact Audio")]
        [Tooltip("Assign a short, dull rock-thump clip. This does not trigger merge visuals or haptics.")]
        [SerializeField] private AudioClip _rockThumpClip;
        [SerializeField, Range(0f, 1f)] private float _rockThumpVolume = 0.8f;
        [SerializeField, Range(0.1f, 3f)] private float _rockThumpPitch = 1f;

        [Header("Optional Impact Hooks")]
        [Tooltip("Connect a platform haptics adapter here without coupling animation code to a haptics package.")]
        [SerializeField] private UnityEvent _onMergeImpact = new();

        private AudioSource _audioSource;
        private bool _reportedMissingVfxPrefab;

        /// <summary>
        /// Creates a self-contained merge beat. State changes are callbacks inside the
        /// sequence, so queued chain merges do not enter Merging before their visual turn.
        /// </summary>
        public Sequence CreateMergeBeat(
            BlobView source,
            BlobView target,
            Vector2Int gridDirection,
            Action onTargetConsumed)
        {
            if (source == null)
                throw new ArgumentNullException(nameof(source));
            if (target == null)
                throw new ArgumentNullException(nameof(target));

            Transform sourceVisual = source.VisualRoot != null
                ? source.VisualRoot
                : source.transform;
            Transform targetVisual = target.VisualRoot != null
                ? target.VisualRoot
                : target.transform;
            Vector3 sourceBaseScale = source.BaseVisualScale;
            Vector3 targetBaseScale = target.BaseVisualScale;
            Vector3 sourceBasePosition = sourceVisual.localPosition;
            Vector3 targetBasePosition = targetVisual.localPosition;
            SortingGroup sourceSorting = source.SortingGroup;
            SortingGroup targetSorting = target.SortingGroup;
            int sourceOriginalLayer = sourceSorting != null
                ? sourceSorting.sortingLayerID
                : 0;
            int targetOriginalLayer = targetSorting != null
                ? targetSorting.sortingLayerID
                : 0;
            int sourceOriginalOrder = sourceSorting != null
                ? sourceSorting.sortingOrder
                : 0;
            int targetOriginalOrder = targetSorting != null
                ? targetSorting.sortingOrder
                : 0;
            int mergeBaseOrder = Mathf.Max(sourceOriginalOrder, targetOriginalOrder);
            Vector3 direction = new(gridDirection.x, gridDirection.y, 0f);
            if (direction.sqrMagnitude < 0.001f)
                direction = Vector3.right;
            direction.Normalize();

            Vector2 travelMultipliers = DirectionalScale(_travelScale, direction);
            Vector2 anticipationMultipliers = DirectionalScale(_anticipationScale, direction);

            Sequence beat = DOTween.Sequence();
            beat.AppendCallback(() =>
            {
                source.BlobMotionAnimator?.SetMerging();
                target.BlobMotionAnimator?.SetMerging();
                sourceVisual.localPosition = sourceBasePosition;
                targetVisual.localPosition = targetBasePosition;
                sourceVisual.localScale = sourceBaseScale;
                targetVisual.localScale = targetBaseScale;

                if (sourceSorting != null)
                    sourceSorting.sortingOrder = mergeBaseOrder + _sourceSortingOffset;
                if (targetSorting != null)
                    targetSorting.sortingOrder = mergeBaseOrder + _targetSortingOffset;
            });

            beat.Append(sourceVisual
                .DOLocalMove(sourceBasePosition - direction * _anticipationBackstep,
                    _anticipationDuration)
                .SetEase(Ease.OutQuad));
            beat.Join(sourceVisual
                .DOScale(Multiply(sourceBaseScale, anticipationMultipliers),
                    _anticipationDuration)
                .SetEase(Ease.OutQuad));
            beat.Join(targetVisual
                .DOScale(Multiply(targetBaseScale, _targetBraceScale),
                    _anticipationDuration)
                .SetEase(Ease.OutQuad));

            beat.Append(source.AnimateMoveTo(
                target.GridPosition,
                _travelDuration,
                Ease.InQuad));
            beat.Join(sourceVisual
                .DOScale(Multiply(sourceBaseScale, travelMultipliers),
                    _travelDuration)
                .SetEase(Ease.InOutQuad));
            beat.Join(sourceVisual
                .DOLocalMove(sourceBasePosition, _travelDuration)
                .SetEase(Ease.OutQuad));

            beat.AppendCallback(() =>
            {
                PlayImpact(
                    target.transform.position,
                    source.MergeEffectColor,
                    target);
            });
            beat.Append(targetVisual
                .DOScale(Vector3.zero, _consumeDuration)
                .SetEase(Ease.InBack));
            beat.Join(sourceVisual
                .DOScale(Multiply(sourceBaseScale, _survivorImpactScale),
                    _consumeDuration)
                .SetEase(Ease.OutQuad));

            beat.Append(sourceVisual
                .DOScale(sourceBaseScale, _settleDuration)
                .SetEase(Ease.OutBack));
            beat.Join(sourceVisual
                .DOLocalMove(sourceBasePosition, _settleDuration)
                .SetEase(Ease.OutQuad));
            beat.OnComplete(() =>
            {
                RestoreSorting(
                    sourceSorting,
                    sourceOriginalLayer,
                    sourceOriginalOrder,
                    targetSorting,
                    targetOriginalLayer,
                    targetOriginalOrder);
                sourceVisual.localPosition = sourceBasePosition;
                sourceVisual.localScale = sourceBaseScale;
                source.BlobMotionAnimator?.SetIdle();
                onTargetConsumed?.Invoke();
            });
            beat.OnKill(() => RestoreSorting(
                sourceSorting,
                sourceOriginalLayer,
                sourceOriginalOrder,
                targetSorting,
                targetOriginalLayer,
                targetOriginalOrder));
            return beat;
        }

        /// <summary>Plays only the shared impact layer, useful for special captures.</summary>
        public void PlayImpact(Vector3 worldPosition, Color blobColor, BlobView sortingAnchor)
        {
            PlayImpactAudio();
            _onMergeImpact?.Invoke();
            SortingGroup sortingGroup = sortingAnchor != null
                ? sortingAnchor.SortingGroup
                : null;
            int sortingLayerId = sortingGroup != null
                ? sortingGroup.sortingLayerID
                : 0;
            int sortingOrder = sortingGroup != null
                ? sortingGroup.sortingOrder + _effectSortingOffset
                : HighestSortingOrder(sortingAnchor) + _effectSortingOffset;
            if (_mergeImpactPrefab == null)
            {
                ReportMissingVfxPrefab();
                return;
            }

            Transform parent = _effectsRoot != null ? _effectsRoot : transform;
            MergeImpactVfx effect = Instantiate(
                _mergeImpactPrefab,
                worldPosition,
                Quaternion.identity,
                parent);
            effect.Play(blobColor, sortingLayerId, sortingOrder);
        }

        /// <summary>
        /// Plays the configured merge contact sound without merge VFX or haptics.
        /// </summary>
        public void PlayImpactAudio()
        {
            EnsureAudioSource();
            if (_mergeImpactClip == null)
                return;

            _audioSource.pitch = _mergeImpactPitch;
            _audioSource.PlayOneShot(_mergeImpactClip, _mergeImpactVolume);
        }

        /// <summary>
        /// Plays only the rock contact sound. It intentionally has no merge VFX,
        /// haptics, consumption, or animation-state transition.
        /// </summary>
        public void PlayRockThumpAudio()
        {
            EnsureAudioSource();
            if (_rockThumpClip == null)
                return;

            _audioSource.pitch = _rockThumpPitch;
            _audioSource.PlayOneShot(_rockThumpClip, _rockThumpVolume);
        }

        private void EnsureAudioSource()
        {
            if (_audioSource != null)
                return;

            _audioSource = GetComponent<AudioSource>();
            if (_audioSource == null)
                _audioSource = gameObject.AddComponent<AudioSource>();
            _audioSource.playOnAwake = false;
            _audioSource.spatialBlend = 0f;
        }

        private void OnValidate()
        {
            _anticipationDuration = Mathf.Max(0.01f, _anticipationDuration);
            _travelDuration = Mathf.Max(0.01f, _travelDuration);
            _consumeDuration = Mathf.Max(0.01f, _consumeDuration);
            _settleDuration = Mathf.Max(0.01f, _settleDuration);
        }

        private static Vector2 DirectionalScale(Vector2 scale, Vector3 direction)
        {
            return Mathf.Abs(direction.x) >= Mathf.Abs(direction.y)
                ? new Vector2(scale.y, scale.x)
                : scale;
        }

        private static Vector3 Multiply(Vector3 baseScale, Vector2 multiplier)
        {
            return new Vector3(
                baseScale.x * multiplier.x,
                baseScale.y * multiplier.y,
                baseScale.z);
        }

        private static int HighestSortingOrder(BlobView view)
        {
            if (view == null)
                return 0;

            int order = 0;
            foreach (SpriteRenderer renderer in view.GetComponentsInChildren<SpriteRenderer>(true))
                order = Mathf.Max(order, renderer.sortingOrder);
            return order;
        }

        private void ReportMissingVfxPrefab()
        {
            if (_reportedMissingVfxPrefab)
                return;

            _reportedMissingVfxPrefab = true;
            Debug.LogWarning(
                "Merge impact VFX has no authored MergeImpactVfx prefab assigned.",
                this);
        }

        private static void RestoreSorting(
            SortingGroup source,
            int sourceLayer,
            int sourceOrder,
            SortingGroup target,
            int targetLayer,
            int targetOrder)
        {
            if (source != null)
            {
                source.sortingLayerID = sourceLayer;
                source.sortingOrder = sourceOrder;
            }

            if (target != null)
            {
                target.sortingLayerID = targetLayer;
                target.sortingOrder = targetOrder;
            }
        }

    }
}
